export default [
  'Javascripter',
  'Frontender',
  'Backender',
  'Technology enthusiast',
  'Japanese student',
  'Emoji fanatic',
  'Problem solver',
  'Self-taught programmer',
  'Details observer',
  'Passionate about coding',
  'Code lover',
  'Natural coder',
  'Results oriented',
  'Best practices promoter',
  'Lifelong learner',
  'Hardcore documenter',
];
